baseURL = "https://dd-4.netlify.app/"
locale = "en-us"
title = "Dashboard Deluxe 3"
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Your centralized hub for quick access to websites and resources."
  disableHiding = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[build]
  [build.buildStats]
    enable = true

  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
    disableWatch = true
