name = "JoRap"
license = "MIT"
licenselink = ""
description = "JoRap Hugo Theme with Tailwind CSS"
homepage = "https://jorap.com"
tags = ["tailwindcss", "responsive"]
features = ["tailwindcss"]
min_version = "0.118.0"

[author]
  name = "JoRap"
  homepage = "https://jorap.com"